version: "3.7"

services:
  web:
    build:
      context: ../
      # Note that this is based on the context dir
      # (Mostly) everything else is based off the
      # compose file's dir
      dockerfile: ./docker/Dockerfile
    command: python -u docker/init.py
    volumes:
      - type: bind
        source: ../
        target: /shamiko
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=docker.settings
    depends_on:
      - memcached
      - postgres
    networks:
      - siteproject-intercontinental-highway
  memcached:
    image: memcached:latest
    restart: always
    entrypoint:
      - memcached
      - -m 512
    networks:
      - siteproject-intercontinental-highway
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
      - POSTGRES_USER=POSTGRES_USER
      - POSTGRES_DB=kasiteproject
    networks:
      - siteproject-intercontinental-highway

# Give the network a name so it's more deterministic
# Otherwise it defaults to <directory>_default
networks:
  siteproject-intercontinental-highway:
    name: siteproject-intercontinental-highway